[package]
name = "philexegis"
version = "0.1.0"
authors = ["Christopher Phillips <shrydar@jaruth.com>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
base64 = "~0.5"
png = "0.7"


[dependencies.conrod]
version = "0.51"
features = ["winit", "glium"]


